size = '(//div[@id="option-label-size-143-item-167"])[2]'
color = '(//div[@id="option-label-color-93-item-53"])[1]'
add_to_cart = '(//span[contains(text(),"Add to Cart")])[2]'
shopping_cart_added = '(//span[contains(text(),"Added")])[2]'
shopping_cart = '//a[contains(.,"shopping cart")]'
