btn_proceed_to_checkout = 'xpath:(//button[@title="Proceed to Checkout"])[2]'
input_street_address = 'xpath://input[@name="street[0]"]'
input_city = 'xpath://input[@name="city"]'
state_option = 'xpath://option[@value="1"]'
input_zip = 'xpath://input[@name="postcode"]'
input_mobile = 'xpath://input[@name="telephone"]'
radio_btn = 'xpath:(//input[@type="radio"])[1]'
btn_next = 'xpath://button[@data-role="opc-continue"]'
btn_place_order = 'xpath:(//button[@type="submit"])[3]'
txt_message = 'xpath://span[contains(.,"Thank you for your purchase!")]'
